### ISSUE TITLE
ログイン機能の実装

### ISSUE THREAD

**Issue by chinen-eita-FTC** [chinen-eita-FTC/flm#1]
書籍管理システムのログイン管理機能の追加

**Comment by takafumi-kurosaki-FTC** [comment]
管理システムのログイン時に、ユーザーを一般ユーザーと管理ユーザーに分けるのはいかがでしょうか。
期間的な問題はあるかと思いますが、将来的な機能の拡張時に役立つのではないかと考えます。

**Comment by chinen-eita-FTC** [comment]
そうですね。
とりあえず以下をTODOとしてまとめます。
## 本チケットでの実装機能一覧
- [x] ログイン画面の実装
- [x] 認証機能の実装
- [ ] 認可機能の実装

**Comment by chinen-eita-FTC** [comment]
#3 のプルリクエストの内容で「ログイン画面の実装」、「認証機能の実装」は確認済、
認可機能はペンディングとして本チケットはいったんクローズする。
