### ISSUE TITLE
蔵書削除機能の追加

### ISSUE THREAD

**Issue by chinen-eita-FTC** [chinen-eita-FTC/flm#6]
# 概要
登録されている蔵書を削除する機能を追加する。

# タスク
- [x] 蔵書削除ページの追加
- [x] 蔵書削除機能の追加

# 完了基準
タスクがすべてフィックス・ペンディングの状態になったことを確認後に
本チケット起票者がクローズする。 #

**Comment by takafumi-kurosaki-FTC** [comment]
テストコードでのエラーが発生いたしました。

先ほどローカルの環境を一旦削除し、クローンした内容で再度昨日までの分でテストを試みましたが、
外部キー関連の部分でテストエラーが発生しております。

下記のエラーコードが発生しております。

1) Tests\Unit\Models\Masters\BookTest::任意の主キーを使用してレコードが1件削除されること
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails (SQL: drop table if exists `m_user_roles`)

他の環境でも同じ現象が起きるか確認をしていただければと思います。

**Comment by takafumi-kurosaki-FTC** [comment]
大変申し訳ございません。
先ほど、DBを削除して再度マイグレーションを行いました結果、エラーなく実行が可能でした。
エラーコードでも(SQL: drop table if exists m_user_roles)とあるとおり、何かしらの誤操作をしてしまったものと思われます。
お手数をおかけいたしました。

**Comment by chinen-eita-FTC** [comment]
蔵書削除画面をモーダルウィンドウにて実装完了し、
動作確認まで行ったっため本チケットはクローズする。
<img width="652" alt="蔵書削除画面" src="https://user-images.githubusercontent.com/48638924/58377707-9fec7400-7fc1-11e9-852a-e4d33a028ad7.PNG">
